### PR TITLE
Load config from different files

### PR DESCRIPTION
**Pull request by rpbaltazar**
Allow one of the configs to be loaded from a global config file
(~/.story_branch)
while others from the project root config file
(.story_branch)

### CODE REVIEW

**Comment by jasonm23** [comment]
@rpbaltazar looks ok.  Please add documentation coverage to README before merge.

**Comment by rpbaltazar** [comment]
I've updated the Readme to try to explicitly explain the situation.

**Comment by jasonm23** [comment]
Cheers Rui, looks ok.

**Comment by jasonm23** [comment]
Published to Rubygems

**Pull request merged**
